title: "Gremlin: Chaos Monkey"
email: gabe@gabewyatt.com
#description: >- # this means to ignore newlines until "baseurl:"
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
baseurl: "/gremlin-chaos-monkey" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  gabestah
#theme: jekyll-theme-modernist
remote_theme: hpstr-jekyll-theme

# Build settings
markdown: kramdown
#theme: minima
plugins:
  - jekyll-feed
  - jekyll-toc

repository: GabeStah/gremlin-chaos-monkey